# Generated by Django 5.1 on 2025-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_delete_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
