<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-04-03 12:50
=======
# Generated by Django 5.1 on 2025-04-03 21:15
>>>>>>> 0576fe6360ea95122319768638aed82cb032e1db

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_delete_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='slug',
<<<<<<< HEAD
            field=models.CharField(max_length=300, unique=True),
=======
            field=models.CharField(max_length=200, unique=True),
>>>>>>> 0576fe6360ea95122319768638aed82cb032e1db
        ),
    ]
